### PR TITLE
Update Autoprefixer and migrate to enb-validation-code

### PR DESCRIPTION
**Pull request by isqua**
Just tested it on my project, works fine.

### CODE REVIEW

**Comment by isqua** [comment]
ping

**Comment by blond** [comment]
Hi! 

In `autoprefixer-core@5.0` was broken backward compatibility: `autoprefixer.default` has been removed.

Need use [browserslist](https://github.com/ai/browserslist). See https://github.com/postcss/autoprefixer-core/issues/26.

**Comment by isqua** [comment]
Added browserslist

**Comment by blond** [comment]
Thanks!

**Comment by blond** [comment]
Released in `v0.3.0`.

**Comment by i-akhmadullin** [comment]
They returned back `autoprefixer.defaults` in next 5.1 version.
`"Return autoprefixer.defaults as alias to current browserslist.defaults."`
https://github.com/postcss/autoprefixer-core/blob/master/ChangeLog.md#51-jianyuan

And `browserslist` is dependency of autoprefixer-core itself:
https://github.com/postcss/autoprefixer-core/blob/master/package.json#L14

**Pull request merged**
